name: flutter_event_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  
  cupertino_icons: ^1.0.4
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  color_utils: ^1.0.0
  mb_contact_form: ^0.0.1
  flutter_email_sender: ^5.0.2
  image_picker: ^0.8.4+4
  mailer: ^5.1.0
  url_launcher: ^6.0.18
  firebase_core: ^1.11.0
  firebase_analytics: ^9.0.5
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  firebase_database: ^9.0.5
  
  # animated_splash_screen: ^1.1.0
  # page_transition: ^2.0.1-nullsafety.0

dev_dependencies:
  button: ^0.0.4
  flutter_test:
    sdk: flutter
  padder: ^1.5.0
  flutter_native_splash: ^1.2.1

flutter_native_splash:
  color: "#e1ddf0"
  image: assets/SPLASH_SCREEN.png
  fill: false
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
