name: flutter_event_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.7.0
  intl: ^0.16.1
  color_utils: ^0.0.1
  mb_contact_form: ^0.0.1

dev_dependencies:
  button: ^0.0.4
  flutter_test:
    sdk: flutter
  padder: ^1.5.0
  flutter_native_splash: ^1.2.1

flutter_native_splash:
  color: "#ffffff"
  image: assets/newlogo.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
